### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nosaJjr** [yasinkuyu/binance-trader#11]
i received this error 

Traceback (most recent call last):
  File "/Users/SoleATCService/Desktop/binance-trader-master/trader.py", line 216, in <module>
    main()
  File "/Users/SoleATCService/Desktop/binance-trader-master/trader.py", line 209, in main
    action(symbol)
  File "/Users/SoleATCService/Desktop/binance-trader-master/trader.py", line 129, in action
    file = open("ORDER", "r") 
IOError: [Errno 2] No such file or directory: 'ORDER'

**Comment by caiorondon** [comment]
If you just read the console I bet you can figure it out the error by yourself.


```
[...]
IOError: [Errno 2] No such file or directory: 'ORDER'
[...]
```

Have you deleted this file? It is on the root of the repository.

This bot is completely experimental and it has yet a lot of cases to cover. To increase your chances of using it correctly, try to change the environment as less as possible.

**Comment by caiorondon** [comment]
@yasinkuyu a solution that I use for dealing with file handling and paths is using `os module`.

```
import os
import path
[...]
open(os.path.join(sys.path[0], "file_to_be_opened"), "r");
```

The first argument of any executions gives that

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/72aca9ced9257dd5e6b3294d88d547a388a3ccb7

**Comment by nosaJjr** [comment]
no i haven't deleted any files
