### ISSUE TITLE
Issue i dont know how to reslove

### ISSUE THREAD

**Issue by xXKingAlexXx** [yasinkuyu/binance-trader#110]
gt: No JSON object could be decoded
Exception in thread Thread-139:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.target(*self.args, **self.kwargs)
  File "./app/Trading.py", line 300, in action
    print ('price:%.8f buyp:%.8f sellp:%.8f-bid:%.8f ask:%.8f' % (lastPrice, buyPrice, profitableSellingPrice, lastBid, lastAsk))
TypeError: float argument required, not NoneType

I keep having this issue. Dont know how to resolve it.

**Comment by WeSpeakCrypto** [comment]
What is your --wait_time?

**Comment by yasinkuyu** [comment]
You will get this error if there is no Internet connection or if you can not connect to the binance server.
