### ISSUE TITLE
how to solve this?

### ISSUE THREAD

**Issue by benjamin638900** [yasinkuyu/binance-trader#12]
Traceback (most recent call last):
  File "trader.py", line 216, in <module>
    main()
  File "trader.py", line 209, in main
    action(symbol)
  File "trader.py", line 132, in action
    lastPrice = get_ticker(symbol)
  File "trader.py", line 116, in get_ticker
    return float(ret["lastPrice"])
KeyError: 'lastPrice'

**Comment by caiorondon** [comment]
You are probably using the wrong symbol as your coin pair. 

If you want to use this bot with BCC, for example, you should put BCCBTC as your symbol.
