### ISSUE TITLE
Insufficient balance & panic selling

### ISSUE THREAD

**Issue by elCapitanoh** [yasinkuyu/binance-trader#124]
Using devx branch, latest commit (Import Tools.py Error fix).

Parameters:
CND/BTC for 0.5% profit, quantity 260, using BNB for fees.

Firstly, I really like the feature that cancels buy orders if they fail to be filled instantly. Thanks for that! :+1: 

Secondly, I've been encountering random "insufficient balance" errors that don't seem valid because the bot continues to trade.

> price:0.00001945 buyp:0.00001942 sellp:0.00001952-bid:0.00001942 ask:0.00001958
Buy order created id:3526544, q:260.00000000, p:0.00001942
Buy order filled... Try sell...
Sell order create id: 3526569
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Order filled
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.

For whatever reason, the bot decided to sell at a loss.
Binance screenshot: https://gyazo.com/402ce7613d8d3a911393520e4d64d4f4

Shortly after, the bot proceeded to make a trade where the sell order wasn't filled instantly, causing it sell for the exact same amount as it bought at (wasting my BNB on fees). If this is supposed to be a feature, please at least let me toggle it off so it doesn't waste my BNB.

> Buy order created id:3526828, q:260.00000000, p:0.00001922
Buy order filled... Try sell...
Sell order create id: 3526852
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Profit loss, called order, 3526852
price:0.00001928 buyp:0.00001922 sellp:0.00001932-bid:0.00001922 ask:0.00001928Stop-loss, sell limit, 1.9222434e-05

Binance screenshot: https://gyazo.com/9d1ec5ba7f3acf182f50f8c8b0e0bd6c

And yes, I have enough BNB to cover the fees of the aforementioned trades.

Thank you for all the time everyone's been investing into testing and developing this thing, it's a neat little community. Keep up the great work! :heart:

**Comment by yasinkuyu** [comment]
Thanks for the details and screenshots. Unfortunately, I can not test it often because there is no balance on my account.
I will fix it as soon as possible.

**Comment by elCapitanoh** [comment]
I appreciate your quick response man! Will definitely consider donating to you and WeSpeakCrypto soon so you guys can continue testing locally.

I solved the panic selling problem by using --stopless 0, but please make it the default. Perhaps add the "check" label on this ticket until it's fixed?

**Comment by dmuzizian** [comment]
![1](https://user-images.githubusercontent.com/15715474/35180331-797d2058-fde0-11e7-9cec-29db8f41709e.jpg)

**Comment by WeSpeakCrypto** [comment]
1: Buy order hold: You can make it wait longer by changing the WAIT_TIME_CHECK_BUY variable inside Trading.py I don't think this should be toggled though. But this is an error for range mode. Didn't thought about that.

2: Stoploss 0: This is already considered. I'll add it and prevent from selling market price. But this will mean bot will wait till it is sold. Other wise. It will just be checking the status of that order.

3: About the flood and UNKOWN_ORDER. Still trying to find the leak there. My thread stopper is not working. :( I didn't yet know what change made it not work.

@elCapitanoh

**Comment by WeSpeakCrypto** [comment]
You can try it under my forked repo now. Remember to use small amounts first. :)

**Comment by nealgentry** [comment]
python trader.py --quantity 20 --symbol BNBETH --profit .2 --stop_loss 0
@yasinkuyu, 2018
Auto Trading for Binance.com. --symbol: BNBETH

... 

Started... --quantity: 20.00000000

0.2% profit scanning for BNBETH 

Between Ask and Bid 0.2% profit hunting
buyp : BuyPrice  (Bid+ --increasing 0.00000100)
sellp: SellPrice (Bid- --decreasing 0.00000100)
... 

price:0.01412600 buyp:0.01411200 sellp:0.01413922-bid:0.01411100 ask:0.01417900
price:0.01412600 buyp:0.01411200 sellp:0.01413922-bid:0.01411100 ask:0.01417900
Buy order created id:12657347, q:20.00000000, p:0.01411200
m: Account has insufficient balance for requested action.
Profit loss, called order, 12657347
Buy order fail (Not filled) Cancel order...
price:0.01412600 buyp:0.01411200 sellp:0.01413922-bid:0.01411100 ask:0.01417900
m: UNKNOWN_ORDER
price:0.01412600 buyp:0.01411200 sellp:0.01413922-bid:0.01411100 ask:0.01417900
Buy order created id:12657349, q:20.00000000, p:0.01411200
m: UNKNOWN_ORDER
m: Account has insufficient balance for requested action.
m: UNKNOWN_ORDER
Profit loss, called order, 12657349
Buy order fail (Not filled) Cancel order...
price:0.01412600 buyp:0.01411100 sellp:0.01413822-bid:0.01411000 ask:0.01417900
m: UNKNOWN_ORDER
price:0.01412600 buyp:0.01412700 sellp:0.01415425-bid:0.01412600 ask:0.01417900
Buy order created id:12657355, q:20.00000000, p:0.01411100
m: UNKNOWN_ORDER
m: UNKNOWN_ORDER
m: Account has insufficient balance for requested action.
Profit loss, called order, 12657355
Buy order fail (Not filled) Cancel order...
price:0.01412600 buyp:0.01412700 sellp:0.01415425-bid:0.01412600 ask:0.01417900
m: UNKNOWN_ORDER
Buy order created id:12657360, q:20.00000000, p:0.01412700
m: UNKNOWN_ORDER
m: UNKNOWN_ORDER
^CTraceback (most recent call last):
  File "trader.py", line 45, in <module>
    t.run()
  File "./app/Trading.py", line 519, in run
    time.sleep(self.wait_time - (endTime - startTime))
KeyboardInterrupt
Profit loss, called order, 12657360
Buy order fail (Not filled) Cancel order...
m: UNKNOWN_ORDER
price:0.01412600 buyp:0.01412800 sellp:0.01415525-bid:0.01412700 ask:0.01417800
m: UNKNOWN_ORDER
Buy order created id:12657367, q:20.00000000, p:0.01412800
Buy order partially filled... Try sell... Cancel remaining buy...
Profit loss, called order, 12657367
m: Filter failure: PRICE_FILTER




even with stoplosss at 0
