### ISSUE TITLE
Getting KeyError: 'orderId'

### ISSUE THREAD

**Issue by Wrexen** [yasinkuyu/binance-trader#139]
Hey. Can someone help me out with this error:

C:\Users\XXX\Desktop\c>trader.py --symbol CNDBTC --max_amount true --profit 0.3 --stop_loss 0
@yasinkuyu, 2018
Auto Trading for Binance.com. --symbol: CNDBTC

0.3% profit scanning for CNDBTC

...

price:0.00001690 buyp:0.00001693 sellp:0.00001695-bid:0.00001690 ask:0.00001695
price:0.00001690 buyp:0.00001693 sellp:0.00001695-bid:0.00001690 ask:0.00001695
price:0.00001690 buyp:0.00001693 sellp:0.00001695-bid:0.00001690 ask:0.00001694
price:0.00001690 buyp:0.00001692 sellp:0.00001694-bid:0.00001689 ask:0.00001690
price:0.00001683 buyp:0.00001686 sellp:0.00001688-bid:0.00001683 ask:0.00001686
price:0.00001686 buyp:0.00001683 sellp:0.00001685-bid:0.00001680 ask:0.00001686
Buy order created id:3792278, q:654.00000000, p:0.00001683
Buy order filled... Try sell...
m: Account has insufficient balance for requested action.
Traceback (most recent call last):
  File "C:\Users\Thurian_2\Desktop\c\trader.py", line 46, in <module>
    t.run()
  File "./app\Trading.py", line 448, in run
    self.action(symbol)
  File "./app\Trading.py", line 340, in action
    self.sell(symbol, quantity, self.order_id, profitableSellingPrice, lastPrice)
  File "./app\Trading.py", line 116, in sell
    sell_id = Orders.sell_limit(symbol, quantity, sell_price)['orderId']
KeyError: 'orderId'

C:\Users\XXX\Desktop\c>

Thanks.

**Comment by se4** [comment]
https://github.com/yasinkuyu/binance-trader/issues/147
