### ISSUE TITLE
Key Error?

### ISSUE THREAD

**Issue by nealgentry** [yasinkuyu/binance-trader#147]
price:0.66850000 buyp:0.66600000 sellp:0.66965500-bid:0.66500000 ask:0.66990000
Buy order created id:2757894, q:20.00000000, p:0.66600000
Profit loss, called order, 2757894
Buy order fail (Not filled) Cancel order...
price:0.66800000 buyp:0.66600000 sellp:0.66965500-bid:0.66500000 ask:0.66980000
Buy order created id:2757900, q:20.00000000, p:0.66600000
Buy order filled... Try sell...
Sell order create id: 2757906
Profit loss, called order, 2757906
m: Filter failure: PRICE_FILTER
Traceback (most recent call last):
  File "trader.py", line 46, in <module>
    t.run()
  File "./app/Trading.py", line 477, in run
    self.action(symbol)
  File "./app/Trading.py", line 369, in action
    self.sell(symbol, quantity, self.order_id, profitableSellingPrice, lastPrice)
  File "./app/Trading.py", line 165, in sell
    if self.stop(symbol, quantity, sell_id, sell_price):
  File "./app/Trading.py", line 233, in stop
    sell_id = sello['orderId']
KeyError: 'orderId'

**Comment by se4** [comment]
same as @nealgentry when i run

`python trader.py --symbol ETHUSDT --quantity 0.03 --profit 0.4`

**Comment by se4** [comment]
printed the sell-order info in Line 132 , Trading.py.

> {'msg': 'Account has insufficient balance for requested action.', 'code': -2010}

**binance-rest-server returned code '-2010':**

https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md

**solution:**
https://github.com/sammchardy/python-binance/issues/74

> I haven't used this project but I had a similar error message with another python exchange wrapper. The problem was in the end that I was reading my funds from the exchange and save it in a variable to use it later in a buy operation. But through data type conversion I got more decimal points than supportet. I had to write a rounding function to get it back to the maximum digits allowed (in my case Satoshi units "one hundred millionth of a single bitcoin") and then it worked again. I never had insufficient funds but my request wasn't supported.
> Maybe this will help you.

**Comment by se4** [comment]
`python trader.py --symbol ETHUSDT --quantity 0.03 --profit 0.4`

**Through Chrome F12 network tools, I found the deal**

You buy 0.03 ETH through REST-API,then you exactaly buy 0.003001 ETH !
you sell 0.03 ETH through REST-API,then you should sell 0.02998 ETH but you exactaly sell 0.003001 ETH through REST-API ! 

**So the solution is**

leave at least 0.001 ETH in your Binance ETH Wallet , then the ETH->USDT deal will be smoothly . So does other tokens.Don't leave your token coin = 0 !

**中文解释**

你通过币安API买0.03个ETH，实际买下来的就是0.03001个ETH。
你通过币安API卖0.03个ETH，实际卖的是0.03001个ETH，而币安允许的是0.02998个ETH。
这一点可以从历时委托中，抓取封包看出来。https://www.binance.com/userCenter/orderHistory.html

解决方案就是：如果你要用程序自动交易这个币，保留被购入售出套利的币种余额不为0，根据币价值留一点即可。

👍 💯

**Comment by nealgentry** [comment]
thank you!
