### ISSUE TITLE
KeyError: 'orderid'

### ISSUE THREAD

**Issue by nealgentry** [yasinkuyu/binance-trader#154]
still having issues with this error.

price:0.01286400 buyp:0.01288000 sellp:0.01289236-bid:0.01284100 ask:0.01286300
price:0.01280600 buyp:0.01284400 sellp:0.01285722-bid:0.01280600 ask:0.01286300
Buy order created id:12953122, q:20.00000000, p:0.01284400
Buy order partially filled... Wait 1 more second...
m: Account has insufficient balance for requested action.
Traceback (most recent call last):
  File "trader.py", line 46, in <module>
    t.run()
  File "./app/Trading.py", line 483, in run
    self.action(symbol)
  File "./app/Trading.py", line 367, in action
    self.sell(symbol, quantity, self.order_id, profitableSellingPrice, lastPrice)
  File "./app/Trading.py", line 146, in sell
    sell_id = Orders.sell_limit(symbol, quantity, sell_price)['orderId']
KeyError: 'orderId'

**Comment by se4** [comment]
https://github.com/yasinkuyu/binance-trader/issues/147
