### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by VasTShadowZz** [yasinkuyu/binance-trader#163]
price:0.00310800 buyp:0.00310620 sellp:0.00312790-bid:0.00310000 ask:0.00310790
Traceback (most recent call last):
  File "trader.py", line 46, in <module>
    t.run()
  File "./app\Trading.py", line 494, in run
    self.action(symbol)
  File "./app\Trading.py", line 302, in action
    lastPrice = float(ticker['lastPrice'])
KeyError: 'lastPrice'

C:\Users\theep\Desktop\binance-trader-WeSpeakCrypto>

**Comment by nealgentry** [comment]
Same Issue.

Traceback (most recent call last):
  File "trader.py", line 46, in <module>
    t.run()
  File "./app/Trading.py", line 494, in run
    self.action(symbol)
  File "./app/Trading.py", line 378, in action
    self.sell(symbol, quantity, self.order_id, profitableSellingPrice, lastPrice)
  File "./app/Trading.py", line 159, in sell
    self.stop(symbol, quantity, sell_id, sell_price)
  File "./app/Trading.py", line 216, in stop
    sell_id = sello['orderId']

**Comment by nealgentry** [comment]
KeyError: 'orderId'
