### ISSUE TITLE
Error in the middle of trading

### ISSUE THREAD

**Issue by PlayboySatoshi** [yasinkuyu/binance-trader#188]
Exception in thread Thread-5009:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./app/Trading.py", line 98, in sell
    if buy_order['status'] == 'FILLED' and buy_order['side'] == "BUY":
TypeError: 'bool' object has no attribute '__getitem__'

Any help please?

**Comment by AxelDeneu** [comment]
Binance where experiencing some problems with their website. This might be the reason your script crashed. Mine crashed too with an uncommon error.
