### ISSUE TITLE
Not able to get this running on Mac

### ISSUE THREAD

**Issue by ahamedvasim83** [yasinkuyu/binance-trader#243]
sudo pip install requests

Error : sudo: pip: command not found

Also, can someone give me steps on executing the following commands on Terminal window.

Python 2.7
    import os
    import sys
    import time
    import config
    import argparse
    import threading
    import sqlite3

**Comment by ahamedvasim83** [comment]
Also getting following error when executing the trade

python trader.py --symbol KMDBTC --amount 0.002 --profit 1
Traceback (most recent call last):
  File "trader.py", line 9, in <module>
    from Trading import Trading
  File "./app/Trading.py", line 17, in <module>
    from Orders import Orders
  File "./app/Orders.py", line 5, in <module>
    from BinanceAPI import BinanceAPI
  File "./app/BinanceAPI.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by FredMichel** [comment]
Try 
python3 trader.py --symbol KMDBTC --amount 0.002 --profit 1
