### ISSUE TITLE
line 417: TypeError: float argument required, not NoneType

### ISSUE THREAD

**Issue by isofish48** [yasinkuyu/binance-trader#244]
An error occurred when executed with the following command. Can you solve this problem?

command:
python trader.py --symbol BCCBTC --quantity 0.01 --p      rofit 1.3 --wait_time 1 --stop_loss 3

Error:
Get Ticker Exeption: HTTPSConnectionPool(host='www.binance.com', port=443): Max retries ex      ceeded with url: /api/v1/ticker/24hr?symbol=BCCBTC (Caused by NewConnectionError('<urllib3      .connection.VerifiedHTTPSConnection object at 0x7f6985badc90>: Failed to establish a new c      onnection: [Errno -3] Temporary failure in name resolution',))
Exception in thread Thread-142:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./app/Trading.py", line 417, in action
    self.logger.debug('price:%.8f buyprice:%.8f sellprice:%.8f bid:%.8f ask:%.8f spread:%.      2f  Originalsellprice:%.8f' % (lastPrice, buyPrice, profitableSellingPrice, lastBid, lastA      sk, spreadPerc, profitableSellingPrice-(lastBid *self.commision)   ))
TypeError: float argument required, not NoneType

**Comment by BatmanPDX** [comment]
Im getting somewhat of the same issue as well. Did Binance change something in their API?
