### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by JunyuanZheng** [yasinkuyu/binance-trader#27]
TypeError: Unicode-objects must be encoded before hashing

```
Traceback (most recent call last):
12/23/2017 3:28:19 PM  File "./trader.py", line 217, in <module>
12/23/2017 3:28:19 PM    main()
12/23/2017 3:28:19 PM  File "./trader.py", line 210, in main
12/23/2017 3:28:19 PM    action(symbol)
12/23/2017 3:28:19 PM  File "./trader.py", line 160, in action
12/23/2017 3:28:19 PM    ORDER_ID = buy_limit(symbol, QUANTITY, buyPrice)
12/23/2017 3:28:19 PM  File "./trader.py", line 44, in buy_limit
12/23/2017 3:28:19 PM    ret = client.buy_limit(symbol, quantity, buyPrice)
12/23/2017 3:28:19 PM  File "/app/BinanceAPI.py", line 50, in buy_limit
12/23/2017 3:28:19 PM    return self._post(path, params)
12/23/2017 3:28:19 PM  File "/app/BinanceAPI.py", line 116, in _post
12/23/2017 3:28:19 PM    query = urlencode(self._sign(params))
12/23/2017 3:28:19 PM  File "/app/BinanceAPI.py", line 100, in _sign
12/23/2017 3:28:19 PM    signature = hashlib.sha256(h).hexdigest()
12/23/2017 3:28:19 PMTypeError: Unicode-objects must be encoded before hashing
```

**Comment by Foof811** [comment]
How many times can this bot loop itself, as in: How many buys and sells it can do continuously before it crashes?

**Comment by JunyuanZheng** [comment]
For me, 0. I am writing my own node.js app now.

**Comment by JunyuanZheng** [comment]
That's why I hate Python.

**Comment by Foof811** [comment]
python is pretty unfriendly with windows. Makes me wish I had a computer i could just throw linux or MacOS on for easier use.

**Comment by Foof811** [comment]
a javascript would be very nice.

**Comment by Foof811** [comment]
and hopefully it would interact more nicely with HTTPS

**Comment by Foof811** [comment]
hoping to make some profit off of crypto day trading without having to dedicate my entire day to watching tickers.

**Comment by mykro92** [comment]
On line 100, change:
`signature = hashlib.sha256(h).hexdigest()`
to
`signature = hashlib.sha256(h.encode('utf-8')).hexdigest()`

**Comment by 001au** [comment]
The solution above worked for me.

**Comment by asghar3166** [comment]
HI,

I am receiving the same issue, thanks for the help in advance

`<ipython-input-29-df4ba1cd1dd4> in sha256(message)
     14 
     15 def sha256(message):
---> 16     return hashlib.sha256(message.encode('utf-8')).hexdigest()
     17 
     18 def sha256b(message):

AttributeError: 'bytes' object has no attribute 'encode'`
