### ISSUE TITLE
Error: Account has insuficient balance to perform this action

### ISSUE THREAD

**Issue by plgonzalezrx8** [yasinkuyu/binance-trader#3]
I'm working on this, but it is an issue. The script should not stop running because lack of funds, it should skip the operation and keep running until funds are available again (The sell is executed).

**Comment by plgonzalezrx8** [comment]
Due to the nature of this error, I'm having problem finding where exactly is originating because it doesn't give you a traceback error, it is just an API return looks like.

**Comment by kingadi111** [comment]
having the same problem . any luck?
Auto Trading for Binance.com (Beta). Enter your symbol. Ex: IOTABTC
POEBTC
%0.5 profit for scanning POEBTC
price:0.00000154 buyp:0.00000162 sellp:0.00000161-bid:0.00000161 ask:0.00000162 BTC:$18600.0
price:0.00000154 buyp:0.00000163 sellp:0.00000162-bid:0.00000162 ask:0.00000163 BTC:$18600.0
price:0.00000155 buyp:0.00000162 sellp:0.00000162-bid:0.00000161 ask:0.00000163 BTC:$18600.0

Order Id: 618906
Percentage of 0.5 profit. Order created from 0.00000162. Profit: 0.00000000 BTC
#####################
Target sell price: 0.00000163
Orders
Order: 618906: 0.000001	1000.000000	0.000000
Sales were made at 1.62e-06 price.
Error: Account has insufficient balance for requested action.

Traceback (most recent call last):
File "C:\bot\trader.py", line 188, in 
main()
File "C:\bot\trader.py", line 181, in main
action(symbol)
File "C:\bot\trader.py", line 160, in action
sell_limit(symbol, QUANTITY, ORDER_ID)
File "C:\bot\trader.py", line 84, in sell_limit
errexit(ret['msg'])
File "C:\bot\trader.py", line 108, in errexit
exit(1)
File "C:\Python27\lib\site.py", line 358, in call
raise SystemExit(code)
SystemExit: 1

**Comment by moonorblue** [comment]
hi there,
just a quick look of the code,
remove `exit(1)` in function `def errexit(msg):` will keep the script running

**Comment by kingadi111** [comment]
******************
Order Id: 644732
Percentage of 0.3 profit. Order created from 0.00000167. Profit: 0.00000000 BTC
#####################
Target sell price: 0.00000168 
Target sell price: 0.00000168 
Target sell price: 0.00000168 
Orders
Order: 644732: 0.000001	1000.000000	0.000000
Sales were made at 1.67e-06 price.
---------------------------------------------
Error: Account has insufficient balance for requested action.
{u'msg': u'Account has insufficient balance for requested action.', u'code': -2010}

this is what happens but it doesnt buy the shares properly , it tries to put in a bid for 000000001 * 100
in binance

**Comment by JordySteyaert** [comment]
I'm having the same issue for WTCBTC. (I have 200WTC on my account)

It starts scanning for 0.5% profit but after a few hundred calls I get this message, without it even making an order. Am I using the correct pairs or should I use BTCWTC?

**Comment by viko42** [comment]
WTCBTC is correct, I think you should have some BTC is your wallet

**Comment by kingadi111** [comment]
it puts the order in wrong on binance also , the price it puts is 100 . did someone screw this up so we couldnt use it? lol

**Comment by TexGoose** [comment]
Has anyone successfully made a profitable trade with this bot? I've run into this error twice now after hundreds of calls on different coins.

**Comment by Foof811** [comment]
Hasn't worked for me either. I got the same error when using IOTABTC and I know for a fact I have plenty of BTC in Binance for it to not show an insufficient balance

**Comment by Foof811** [comment]
Still getting the error. hmm.

**Comment by SoftMandar** [comment]
I had the same error ... and i figured out that balance is referred as quantity , so basically each order you make binance takes something called  FEE. Any transaction you make you need to decrease that FEE ,so in my case with IOSTETH was new_quantity = int(quantity - ((0.050) * quantity)/100)) , it takes 0.050 % from my quantity each time i want to sell on limit, solved it for me.
