### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by MaticConradi** [yasinkuyu/binance-trader#62]
Exception in thread Thread-4518:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "trader.py", line 327, in action
    buyPrice = lastBid + option.increasing
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

No JSON object could be decoded
No JSON object could be decoded

**Comment by yasinkuyu** [comment]
symbol?

**Comment by MaticConradi** [comment]
FUNBTC

**Comment by yasinkuyu** [comment]
This error occurs when the symbol is typed incorrectly or the response is not received from the server.

**Comment by MaticConradi** [comment]
As far as I know, FUNBTC is correct. Therefore I guess it’s an issue on Binance’s side. Thanks anyway and thanks for your work!
